services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
         - "80:80"
    environment:
         - ASPNETCORE_ENVIRONMENT=Production
    volumes:
         - ./media:/app/wwwroot/qrcodes
